name: Post Welcome Comment

on: 
  pull_request:
    types: [opened]

jobs:
  build:
    name: Post Welcome Job
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, World!!!!
      - run: gh pr comment $PR_URL --body "Welcome to the repository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
